from __future__ import annotations

from typing import Any, Dict, Optional, Protocol

from ..core.api_models import (
    DeviceInfoResponse,
    DeviceNameResponse,
    PairDeviceResponse,
    PairingCodeResponse,
    StoreMessageResponse,
    SyncDatabaseResponse,
    SyncResponse,
)


class DbService(Protocol):
    async def store_message(self, payload: Dict[str, Any]) -> StoreMessageResponse: ...
    async def get_oplog(self, dataset_id: Optional[str], limit: int, offset: int) -> Dict[str, Any]: ...
    async def get_messages(self, dataset_id: Optional[str], limit: int, offset: int) -> Dict[str, Any]: ...
    async def replay_projection(self, dataset_id: Optional[str]) -> Dict[str, Any]: ...
    async def reset_database(self) -> Dict[str, Any]: ...
    async def sync_database(self) -> SyncDatabaseResponse: ...
    async def backup_database(self, encrypted: bool) -> Any: ...
    async def restore_database(self, file, authenticated_user_id: str, encrypted: bool) -> Dict[str, Any]: ...


class SyncService(Protocol):
    async def trigger_sync(self) -> SyncResponse: ...


class DeviceService(Protocol):
    async def get_pairing_code(self) -> PairingCodeResponse: ...
    async def pair_device(self, pairing_code: str, keep_existing_data: bool) -> PairDeviceResponse: ...
    async def get_device_info(self, context: Optional[Dict[str, Any]] = None) -> DeviceInfoResponse: ...
    async def set_device_name(self, device_name: str) -> DeviceNameResponse: ...


class LLMService(Protocol):
    async def generate(self, payload: Dict[str, Any]) -> Dict[str, Any]: ...
    async def list_ollama_models(self) -> Dict[str, Any]: ...
