"""Shared batching limits for enrichment/signal jobs."""

from __future__ import annotations

MAX_JOB_MESSAGES = 500
TOPIC_BATCH_CONCURRENCY = 4
URL_CLASSIFICATION_BATCH_SIZE = 32
DIMENSION_SUMMARY_MAX_RECORDS = 50
DIMENSION_SUMMARY_RECORD_CHARS = 500
DIMENSION_SUMMARY_MAX_TOTAL_CHARS = 12_000
