#!/usr/bin/env python3
"""Arm the owner-database tripwire around a gate leg that is NOT pytest.

``tests/live_db_watch`` wraps ``sqlite3.connect`` and refuses any read-write
open of the owner's real ``~/.topos`` database. Until now the only thing that
installed it was ``tests/conftest.py``, so it covered exactly one of ``just
gate``'s seven legs' worth of Python — the pytest ones. The other legs run their
own interpreters, and one of them was not hermetic:

    $ just gate
    ...
    INFO: Serving database /Users/<owner>/.topos/database.db (source=slot, profile=personaldb, schema=62)
    DEBUG: Ensured table browser_visits exists

That is leg 7, ``scripts/release_smoke_test.py``, booting the built wheel's
FastAPI app against the owner's live file and running ``CREATE TABLE IF NOT
EXISTS`` on it. The thing a developer runs before every release opened the
database it exists to protect, and the guard could not see it because the guard
lives in a pytest plugin and that leg is a subprocess tree three interpreters
deep (``uv run python`` → venv ``python`` → ``topos-node``).

This module closes that from the other end. It arms the SAME guard module —
one spelling, no second implementation to drift — in this process and, via a
generated ``sitecustomize.py`` on ``PYTHONPATH``, in every Python child the leg
spawns, including ones in a different virtualenv running a different Python.

    uv run python scripts/live_db_tripwire.py scripts/release_smoke_test.py
    uv run python scripts/live_db_tripwire.py --command uv build

WHY A ``sitecustomize`` AND NOT ``PYTHONPATH=<repo root>``: putting the repo on
a child's path would let the smoke venv import THIS checkout's ``topos``
package, shadowing the installed wheel and deleting the entire point of a
release smoke test. The generated directory holds one file, and that file loads
the guard by absolute path without adding the repo to ``sys.path``.

THE INSTRUMENT IS CHECKED BEFORE IT IS TRUSTED. ``site.execsitecustomize``
swallows exceptions — an import error there prints a warning and the process
runs on, unarmed and silent, which is the failure mode this whole area exists to
cure. So :func:`verify_armed` runs a positive control in a child interpreter
first: it arms a throwaway path as owner data, asserts the connect is refused,
and asserts the refusal landed before SQLite created the file (a guard that
lets a 0-byte file through has already lost). It never names ``~/.topos`` — a
tripwire that has to touch the owner's database to prove itself is the bug.

REFUSING IS NOT REPORTING, AND HERE THAT GAP IS LOAD-BEARING. The first armed
run of this module against the unfixed smoke test refused the connect and the
leg still exited 0: ``topos.core.state._open_owner_db_connection`` catches the
failure, logs ``WARNING: Failed to create database connection``, and the app
serves ``/healthcheck`` from a degraded path — so ``app_boot_ok`` and
``release_smoke_ok`` both printed. A guard that only raises is invisible to any
caller that swallows exceptions, and a guard nobody can see is a guard that gets
regressed. Every armed child therefore APPENDS its findings to a journal file
(``TOPOS_LIVE_DB_JOURNAL``) from an ``atexit`` hook, and the parent fails the
leg if that file has anything in it — independent of exit codes, and independent
of whether the child chose to notice.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import runpy
import subprocess
import sys
import tempfile
from pathlib import Path
from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parent.parent

#: The one implementation of the guard. Loaded by path rather than imported as
#: ``tests.live_db_watch`` so this works from a checkout where ``tests`` is not
#: importable, and so the child (which must not see the repo on sys.path) uses
#: the identical file.
WATCH_MODULE_PATH = REPO_ROOT / "tests" / "live_db_watch.py"

#: Absolute path of the guard module, handed to children.
ENV_WATCH_MODULE = "TOPOS_LIVE_DB_WATCH_MODULE"

#: What a child calls itself in a refusal message. There is no node id outside
#: pytest, and "<collection>" would be a lie.
ENV_WATCH_LABEL = "TOPOS_LIVE_DB_WATCH_LABEL"

#: Append-only file every armed process writes its findings to. The parent owns
#: the verdict; a child that swallowed the refusal does not get a vote.
ENV_WATCH_JOURNAL = "TOPOS_LIVE_DB_JOURNAL"

_SITECUSTOMIZE = '''\
"""Generated by scripts/live_db_tripwire.py. Arms the owner-database guard.

Imported automatically by every interpreter that has this directory on
PYTHONPATH, which is how the tripwire reaches a child in another virtualenv.

Only ONE sitecustomize is ever imported by CPython, so this shadows any other
on the path. Nothing in this repo ships one; if a machine does, note that the
tripwire wins for the duration of the leg.
"""

import atexit
import os
import sys


def _journal(module, label):
    """Append what this process recorded, so a swallowed refusal still counts.

    O_APPEND with one write() per finding: several children of the same leg
    share this file and there is no lock between them, and POSIX makes an
    append under PIPE_BUF atomic. A finding is one line for that reason -- the
    origin frames are joined with " | " rather than newlines.
    """
    path = os.environ.get({env_watch_journal!r})
    if not path:
        return
    findings = module.opens()
    if not findings:
        return
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_APPEND, 0o600)
    try:
        for found in findings:
            origin = " | ".join(found.origin.splitlines())
            verb = "refused" if found.refused else "ALLOWED"
            line = "%s\\t%s\\t%s\\tpid=%d\\t%s\\t%s\\n" % (
                verb, label, found.path, os.getpid(), sys.executable, origin.strip()
            )
            os.write(fd, line.encode("utf-8", "replace"))
    finally:
        os.close(fd)


def _arm() -> None:
    path = os.environ.get({env_watch_module!r})
    if not path:
        return
    import importlib.util

    spec = importlib.util.spec_from_file_location("topos_live_db_watch", path)
    if spec is None or spec.loader is None:
        raise ImportError("live-db tripwire: cannot load guard from " + path)
    module = importlib.util.module_from_spec(spec)
    sys.modules["topos_live_db_watch"] = module
    spec.loader.exec_module(module)
    module.install()
    label = os.environ.get({env_watch_label!r}) or "<non-pytest process>"
    module.set_current_test(label)
    atexit.register(_journal, module, label)


try:
    _arm()
except Exception as exc:  # noqa: BLE001
    # site.execsitecustomize swallows this, so SAY IT. verify_armed() is the
    # half that actually fails the leg; this line is for the human reading a
    # log after the fact.
    sys.stderr.write(
        "live-db tripwire: FAILED TO ARM in %s (%r). This interpreter can "
        "reach the owner's database unnoticed.\\n" % (sys.executable, exc)
    )
    raise
'''

#: Run in a child with the tripwire env. Proves the guard is installed, that it
#: refuses by default, and that the refusal beats SQLite to the filesystem.
_PROBE = """\
import os
import sqlite3
import sys
import tempfile

module = sys.modules.get("topos_live_db_watch")
if module is None:
    raise SystemExit(
        "live-db tripwire: NOT ARMED in %s -- sitecustomize did not run" % sys.executable
    )

with tempfile.TemporaryDirectory(prefix="tripwire-probe-") as tmp:
    probe = os.path.join(tmp, "pretend-owner.db")
    with module.watching(probe):
        try:
            sqlite3.connect(probe)
        except RuntimeError:
            refused = True
        else:
            refused = False
    if not refused:
        raise SystemExit("live-db tripwire: installed but NOT refusing in %s" % sys.executable)
    if os.path.exists(probe):
        raise SystemExit("live-db tripwire: refused only AFTER sqlite created the file")

print("tripwire_armed " + sys.executable)
"""


def load_watch_module() -> ModuleType:
    """The guard module, loaded by path. Cached by ``sys.modules``."""
    cached = sys.modules.get("topos_live_db_watch")
    if cached is not None:
        return cached
    spec = importlib.util.spec_from_file_location(
        "topos_live_db_watch", WATCH_MODULE_PATH
    )
    if spec is None or spec.loader is None:  # pragma: no cover - packaging accident
        raise SystemExit(f"live-db tripwire: cannot load guard from {WATCH_MODULE_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules["topos_live_db_watch"] = module
    spec.loader.exec_module(module)
    return module


def write_sitecustomize(directory: Path) -> Path:
    """Materialise the arming stub into ``directory``; return that directory."""
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "sitecustomize.py").write_text(
        _SITECUSTOMIZE.format(
            env_watch_module=ENV_WATCH_MODULE,
            env_watch_label=ENV_WATCH_LABEL,
            env_watch_journal=ENV_WATCH_JOURNAL,
        ),
        encoding="utf-8",
    )
    return directory


def child_env(
    env: dict[str, str] | None = None,
    *,
    directory: Path,
    label: str = "<non-pytest process>",
    journal: Path | None = None,
) -> dict[str, str]:
    """A copy of ``env`` that arms the tripwire in any Python child."""
    out = dict(env if env is not None else os.environ)
    stub_dir = str(write_sitecustomize(directory))
    existing = out.get("PYTHONPATH")
    out["PYTHONPATH"] = f"{stub_dir}{os.pathsep}{existing}" if existing else stub_dir
    out[ENV_WATCH_MODULE] = str(WATCH_MODULE_PATH)
    out[ENV_WATCH_LABEL] = label
    if journal is not None:
        out[ENV_WATCH_JOURNAL] = str(journal)
    return out


def verify_armed(python: str | os.PathLike, env: dict[str, str]) -> str:
    """Positive control. Raises ``SystemExit`` if ``python`` is not guarded.

    Runs with the journal unset: the probe deliberately trips the guard against
    a throwaway path, and a self-check that wrote its own success into the
    evidence file would make every leg look like a violation.
    """
    probe_env = dict(env)
    probe_env.pop(ENV_WATCH_JOURNAL, None)
    result = subprocess.run(
        [str(python), "-c", _PROBE],
        env=probe_env,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise SystemExit(
            "live-db tripwire self-check FAILED for "
            f"{python}:\n{result.stdout}{result.stderr}"
        )
    return result.stdout.strip()


def journal_findings(journal: Path) -> list[str]:
    try:
        text = journal.read_text(encoding="utf-8")
    except FileNotFoundError:
        return []
    return [line for line in text.splitlines() if line.strip()]


def report(journal: Path, module: ModuleType) -> int:
    """0 if this leg reached no owner data, 1 otherwise. Prints what it found.

    Reads the journal rather than trusting the leg's exit code, because the
    unfixed smoke test exits 0 while a refusal is in flight -- see the module
    docstring.
    """
    findings = journal_findings(journal)
    findings += [
        f"refused\t{entry.nodeid}\t{entry.path}\tpid={os.getpid()}\t{sys.executable}\t"
        + " | ".join(entry.origin.splitlines()).strip()
        for entry in module.opens()
    ]
    if not findings:
        return 0
    print("", file=sys.stderr)
    print("=" * 78, file=sys.stderr)
    print("LIVE-DB TRIPWIRE: this gate leg reached the owner's database.", file=sys.stderr)
    print("", file=sys.stderr)
    for line in findings:
        print("  " + line, file=sys.stderr)
    print("", file=sys.stderr)
    print(
        "Every line above was REFUSED, so nothing was written -- but the leg is\n"
        "still a code path that resolves the owner's real database on a developer\n"
        "machine. Point it at a scratch file (TOPOS_DATABASE_PATH).",
        file=sys.stderr,
    )
    print("=" * 78, file=sys.stderr)
    return 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Run a gate leg with the owner-database tripwire armed."
    )
    parser.add_argument(
        "--label",
        default=None,
        help="Name this leg carries in a refusal message (default: the target)",
    )
    parser.add_argument(
        "--command",
        action="store_true",
        help="Treat the target as an executable to spawn, not a Python script to run here",
    )
    parser.add_argument("target", help="Python script, or executable with --command")
    parser.add_argument("rest", nargs=argparse.REMAINDER)
    args = parser.parse_args(argv)

    label = args.label or f"<gate leg: {args.target}>"
    module = load_watch_module()
    module.install()
    module.set_current_test(label)

    with tempfile.TemporaryDirectory(prefix="topos-tripwire-") as tmp:
        journal = Path(tmp) / "owner-db-opens.tsv"
        env = child_env(
            os.environ, directory=Path(tmp), label=label, journal=journal
        )
        print(f"live-db tripwire: {verify_armed(sys.executable, env)}", flush=True)
        os.environ.update(
            {
                "PYTHONPATH": env["PYTHONPATH"],
                ENV_WATCH_MODULE: env[ENV_WATCH_MODULE],
                ENV_WATCH_LABEL: env[ENV_WATCH_LABEL],
                ENV_WATCH_JOURNAL: env[ENV_WATCH_JOURNAL],
            }
        )

        if args.command:
            completed = subprocess.run([args.target, *args.rest], env=env)
            status = completed.returncode
        else:
            script = Path(args.target)
            sys.argv = [str(script), *args.rest]
            try:
                runpy.run_path(str(script), run_name="__main__")
                status = 0
            except SystemExit as exc:
                status = exc.code if isinstance(exc.code, int) else (0 if exc.code is None else 1)

        verdict = report(journal, module)

    return status or verdict


if __name__ == "__main__":
    raise SystemExit(main())
