"""The explicit-wording rule, sentence by sentence. Every sentence here is invented.

Both directions for every guarded and every framed word: the ordinary use that must not flag beside the explicit
use that must, so that widening a guard or a frame has to answer for the other side.
"""

from __future__ import annotations

import inspect

import pytest

from topos.sanitization import explicit_wording as ew
from topos.sanitization.explicit_wording import RULE_ID, TIER_PHRASE, TIER_UNAMBIGUOUS, Verdict, evaluate

U, P, N = TIER_UNAMBIGUOUS, TIER_PHRASE, None

#: (text, tier) -- N: does not flag; U: unambiguous vocabulary; P: a phrase around an ambiguous word.
CASES = [
    ('8:00 gym, 9:30 standup, 11:00 wrote the migration, lunch with the team', N),
    ('Dinner with my partner at the new place, then a long walk home.', N),
    ('Kill the process, ship the hot fix and crush the bug before lunch.', N),
    ('That was a damn good burger, holy shit.', N),
    ('What the fuck is this build doing', N),
    ('', N),
    ('   ', N),
    ('12345 !!!', N),
    ('The NSFW classifier flagged too many rows; we need a better nsfw filter.', N),
    ('She looked sexy in that dress and he was very charming.', N),
    ('We need to buy condoms and lingerie is on sale.', N),
    ('The doctor examined the penis, vagina and breast tissue samples.', N),
    ('xxx see you soon xxx', N),
    ('This content is explicit about the terms of the contract.', N),
    ('he asked for a blowjob', U),
    ('gave him a blow job', U),
    ('a quick handjob', U),
    ('she had an orgasm', U),
    ('They were sexting all night', U),
    ('watched some hentai', U),
    ('bought a dildo online', U),
    ('skipped the foreplay', U),
    ('into BDSM', U),
    ('doggy style', U),
    ('the missionary position', U),
    ('a new butt plug', U),
    ('my fuck buddy texted', U),
    ('his fuckbuddy', U),
    ('she touched her clit', U),
    ('erotic stories', U),
    ('ejaculation came quickly', U),
    ('pornhub tab', U),
    ('ORGASM', U),
    ('Sexting', U),
    ('Sex: M', N),
    ('age and sex of each participant', N),
    ('sex ratio at birth', N),
    ('same-sex marriage', N),
    ('the opposite sex', N),
    ('biological sex differences', N),
    ('sex education in schools', N),
    ('a registered sex offender', N),
    ('sex trafficking ring exposed', N),
    ('Sex and the City reruns', N),
    ('group by sex and age', N),
    ('sex-linked genes', N),
    ('sex chromosomes', N),
    ('sex appeal', N),
    ('organisms that have sex chromosomes', N),
    ('twins that have the same sex', N),
    ('we had sex', P),
    ('I want to have sex tonight', P),
    ('they were having sex', P),
    ("haven't had sex in months", P),
    ('we had really great sex', P),
    ('great sex', P),
    ('oral sex', P),
    ('anal sex', P),
    ('phone sex', P),
    ('sex with her', P),
    ('sex with a guy from work', P),
    ('the sex was amazing', P),
    ('sex was really good', P),
    ('sex tonight?', P),
    ('sex last night', P),
    ('my sex life is dead', P),
    ('a healthy sex life matters', N),
    ('bought a sex toy', P),
    ('a sex tape', P),
    ('had a sex dream', P),
    ('the association of sex with outcome', N),
    ('male sex with higher risk', N),
    ('I need sex', P),
    ('she wanted sex', P),
    ('no sex for a month', P),
    ('no sex differences were found', N),
    ('sexual assault charges', N),
    ('sexual orientation', N),
    ('sexual harassment training', N),
    ('sexually transmitted infection', N),
    ('sexual reproduction in plants', N),
    ('a sexual fantasy', P),
    ('sexual pleasure', P),
    ('sexually aroused', P),
    ('sexually frustrated', P),
    ('sexual arousal', P),
    ('it aroused suspicion', N),
    ('the talk aroused my curiosity', N),
    ('aroused from sleep by the noise', N),
    ('I was so aroused', P),
    ('she got aroused', P),
    ('I was aroused by him', P),
    ('he was aroused by the noise', N),
    ('physiological arousal levels', N),
    ('turned on the lights', N),
    ('I turned on the heater', N),
    ('the alarm was turned on', N),
    ('notifications are turned on by default', N),
    ('it was turned on by the admin', N),
    ('the dog turned on me', N),
    ('he turned on her', N),
    ('she turned me on to jazz', N),
    ('I was turned on to this band', N),
    ('turn it on', N),
    ('turn them on', N),
    ('turn on a dime', N),
    ('take a turn on the swings', N),
    ('the turn-on voltage is 0.7 V', N),
    ('turn-on time of the transistor', N),
    ('I was so turned on', P),
    ('she was really turned on', P),
    ("I'm turned on", P),
    ('got me so turned on', P),
    ('I was turned on by her', P),
    ('that turns me on', P),
    ('it turned her on', P),
    ('you turn me on', P),
    ('what turns you on', P),
    ('that is a huge turn on', P),
    ('such a turn on', P),
    ('a real turn-on', P),
    ('my turn ons', P),
    ('biggest turn-ons', P),
    ('hook up the monitor', N),
    ('I hooked up the printer', N),
    ('we hooked up the trailer', N),
    ('hook me up with a discount', N),
    ('hooked up to the wifi', N),
    ('we hooked up with the vendor', N),
    ('I hooked up with him for lunch', N),
    ('the sewer hookup', N),
    ('RV hookups at the campsite', N),
    ('a cable hookup fee', N),
    ('hookup culture on campus', N),
    ('I have a hookup for tickets', N),
    ('we hooked up', P),
    ('we hooked up last night', P),
    ('they totally hooked up', P),
    ('I hooked up with her', P),
    ('hooked up with a guy from the bar', N),
    ('I hooked up with a guy from the bar', P),
    ('we ended up hooking up', P),
    ('wanna hook up?', P),
    ('did you hook up with him', P),
    ('a random hookup', P),
    ('tinder hookups', P),
    ('my hookups', P),
    ('make out the words', N),
    ('I could not make out what he said', N),
    ('hard to make out.', N),
    ('made out of wood', N),
    ('made out a check', N),
    ('we made out like bandits', N),
    ('we made out okay', N),
    ('he made out well in the sale', N),
    ('it was made out to be worse', N),
    ('made out with a profit', N),
    ('we made out', P),
    ('we made out in the car', P),
    ('I made out with her', P),
    ('made out with him', P),
    ('they were making out', P),
    ('we started making out', P),
    ('wanna make out', P),
    ('I want to make out', P),
    ('making out with a stranger', P),
    ('we made out for a while', P),
    ('I got laid off', N),
    ('the cable was laid last week', N),
    ('she got laid out by the flu', N),
    ('laid the table', N),
    ('he got laid', P),
    ('trying to get laid', P),
    ('getting laid tonight', P),
    ('went down on one knee', N),
    ('prices went down on Tuesday', N),
    ('it all went down on her birthday', N),
    ('she went down on him', P),
    ('he went down on her', P),
    ('going down on me', P),
    ('we ate out tonight', N),
    ('eating us out of house and home', N),
    ('ate me out of house and home', N),
    ('he ate her out', P),
    ('eat me out', P),
    ('that guy is a jerk', N),
    ('what a jerk off', N),
    ('Jack is off to work', N),
    ('take the jack off the car', N),
    ('he jerked off the road', N),
    ('jerking off', P),
    ('he jacked off', P),
    ('I jerk off', P),
    ('she jerked him off', P),
    ('wants to jack off', P),
    ('this sucks', N),
    ('suck it up', N),
    ('she sucked him off', P),
    ('fuck you', N),
    ('fuck him, he is a jerk', N),
    ('oh fuck me that is expensive', N),
    ('we fucked up', N),
    ('we fucked it up', N),
    ('they fucked us over', N),
    ('that fucked me over', N),
    ('I am going to fuck you up', N),
    ('stop fucking with me', N),
    ('fucking great', N),
    ('it is fucking me up', N),
    ('we fucked around', N),
    ('we fucked', P),
    ('we fucked all night', P),
    ('they fucked in the car', P),
    ('I fucked her', P),
    ('he was fucking her', P),
    ('I want to fuck you', P),
    ('she fucked me so hard', P),
    ("I'd fuck him", P),
    ('graduated summa cum laude', N),
    ('magna cum laude', N),
    ('cum laude', N),
    ('kitchen-cum-diner', N),
    ('a bedroom cum study', N),
    ('the cum sum column', N),
    ('cum_sum = x', N),
    ('cum dividend shares', N),
    ('cum grano salis', N),
    ('cum. total is 40', N),
    ('his cum laude diploma', N),
    ("I'm gonna cum", P),
    ('made me cum', P),
    ('he cum inside', P),
    ('I want to cum', P),
    ('his cum', P),
    ('she made him cum twice', P),
    ('cumming', U),
    ('Alan Cumming was great in it', N),
    ('we drove to Cumming', N),
    ('i was cumming', U),
    ('he is so anal about formatting', N),
    ('anal-retentive', N),
    ('an anal fissure', N),
    ('anal glands of the dog', N),
    ('data anal notes', N),
    ('anal sex', P),
    ('we tried anal', P),
    ('she is into anal', P),
    ('anal beads', P),
    ('an oral exam', N),
    ('oral hygiene', N),
    ('gave an oral presentation', N),
    ('gave me oral antibiotics', N),
    ('he gave her oral', P),
    ('she got oral', P),
    ('gave oral', P),
    ('Dick Van Dyke', N),
    ('my friend Dick called', N),
    ("don't be a dick", N),
    ('what a dick move', N),
    ('those dicks at the office', N),
    ("Dick's Sporting Goods", N),
    ('big dick energy', N),
    ('his dick move', N),
    ('sent a dick pic', P),
    ('suck my dick', P),
    ('his dick', P),
    ('a big dick', P),
    ('sucking dick', P),
    ('he is a cunt', N),
    ('her cunt', P),
    ('visible to the naked eye', N),
    ('the naked truth', N),
    ('naked short selling', N),
    ('a naked domain', N),
    ('naked burrito bowl', N),
    ('slept naked because of the heat', N),
    ('nude heels', N),
    ('a nude beach', N),
    ('the nudes palette', N),
    ('Renaissance nudes', N),
    ('nude lipstick', N),
    ('naked pics', P),
    ('we got naked', P),
    ('I saw her naked', P),
    ('naked in bed', P),
    ('naked together', P),
    ('nude photos', P),
    ('send nudes', P),
    ('she sent me nudes', P),
    ('her nudes leaked', P),
    ('topless selfie', P),
    ('a cock and bull story', N),
    ('cock-a-doodle-doo', N),
    ('what a cock-up', N),
    ('the cock crowed at dawn', N),
    ('cock the hammer', N),
    ('he cocked his head', N),
    ('cock his head', N),
    ('cock of the walk', N),
    ('the ball cock is broken', N),
    ('Mr Cock taught maths', N),
    ('his cock', U),
    ('suck cock', U),
    ('cocks', U),
    ('pussy cat', N),
    ('pussy willow', N),
    ('Pussy Riot concert', N),
    ("don't be a pussy", N),
    ('you pussy', N),
    ('what a pussy', N),
    ('her pussy', U),
    ('wet pussy', U),
    ('blue tits at the feeder', N),
    ('great tits and coal tits', N),
    ('it all went tits up', N),
    ('calm your tits', N),
    ('gets on my tits', N),
    ('nice tits', U),
    ('her tits', U),
    ('food porn', N),
    ('earth porn subreddit', N),
    ('revenge porn law', N),
    ('a porn filter', N),
    ('porn detection classifier', N),
    ('anti-porn campaign', N),
    ('child pornography laws', N),
    ('detect pornography', N),
    ('he watched porn', U),
    ('porn', U),
    ('a pornographic film', U),
    ('porno', U),
    ('intellectual masturbation', N),
    ('mental masturbation', N),
    ('he was masturbating', U),
    ('masturbation', U),
    ('a horny toad', N),
    ('horny goat weed', N),
    ("I'm so horny", U),
    ('horny', U),
    ('pulled a boner on the test', N),
    ('he got a boner', U),
    ('erection of the steel frame', N),
    ('steel erection crew', N),
    ('an erection', U),
    ('an orgy of spending', N),
    ('an orgy', U),
    ('kinky hair', N),
    ('kinky curls', N),
    ('kinky stuff', U),
    ('our threesome teed off at nine', N),
    ('a threesome on the golf course', N),
    ('had a threesome', U),
    ('he has a hard-on for regulations', N),
    ('it was hard on him', N),
    ('he got a hard-on', U),
    ('a second-hand job', N),
    ('a hand job', U),
    ('SO HORNY', U),
    ('so hornyyyy', U),
    ('sooo horny', U),
    ('hоrny', U),
    ('ho\u200brny', U),
    ('we had sеx', P),
    ('ｓｅｘ with her', P),
    ('*horny*', U),
    ('"horny"', U),
    ('_horny_', U),
    ('I was so turned on…', P),
    ('we had sex. Sex: M', P),
    ('had. sex', N),
    ('turned\non', N),
    ('we hooked up 🔥', P),
    ('café pussy willow', N),
    ('I’m so turned on', P),
    ('the rattlesnake has horny segments at the end of its tail', N),
    ('a beak with a horny tip', N),
    ('corals with a horny skeleton', N),
    ('horny plates cover the armadillo', N),
    ('feeling horny tonight', U),
    ('horny af', U),
    ('convert a cock into a capon', N),
    ('a young domestic cock', N),
    ('the cock crowed at dawn', N),
    ('a small cock or faucet for draining', N),
    ('cocks the firearm', N),
    ("cock one's head", N),
    ('rooks, finches, sparrows, tits and warblers at the feeder', N),
    ('tits and robins nested in the garden', N),
    ('kinky telephone cords', N),
    ('a kinky cable', N),
    ('kinky sex', U),
    ('here pussy pussy, the cat purred', N),
    ('she made out that she knew nothing', N),
    ('we hooked up that night', P),
    ('we hooked up that it mattered', N),
    ('steam cock', N),
    ('the hen and the cock', N),
    ('he gets boners in class', U),
    ('he pulls boners on every exam', N),
    ('he cums fast', P),
    ('the cums column in the report', N),
    ('sucking dicks', P),
    ('he has eaten her out', P),
    ('we have eaten out twice this week', N),
    ('he eats her out', P),
    ('she eats out a lot', N),
    ('eating her out', P),
    ("let's eat out tonight", N),
    ('morning erections', U),
    ('the erections of the towers', N),
    ('I was fuckin her', P),
    ('fuckin great weather', N),
    ('he fucks her', P),
    ('she fucks him hard', P),
    ('this fucks him over', N),
    ('it fucks me up', N),
    ('she hooks up with strangers', P),
    ('she hooks up the trailer', N),
    ('hooking up the speakers', N),
    ('he jacks off', P),
    ('he jacks up the car', N),
    ('jacking off', P),
    ('jacking up the price', N),
    ('I jacked up the car', N),
    ('he jerks off', P),
    ('the bus jerks forward', N),
    ('the jerking motion of the train', N),
    ('she makes out with him', P),
    ('she makes out a check', N),
    ('making out the details', N),
    ('he masturbates daily', U),
    ('she masturbated', U),
    ('I masturbate', U),
    ('masturbatory fantasies', U),
    ('an intellectual masturbatory exercise', N),
    ('wild orgies', U),
    ('orgies of violence', N),
    ('he looked at pornography', U),
    ('the pornographic filter caught it', N),
    ('she sucks him off', P),
    ('the vacuum sucked up the dust', N),
    ('sucking on a lemon', N),
    ('threesomes', U),
    ('threesomes on the golf course', N),
    ('turning me on', P),
    ('turning on the lights', N),
    ('the heater turns on at six', N),
    ('such a turnon', P),
    ('the turnon voltage', N),
    ('my turnons', P),
    ('turnons delay of the switch', N),
    ('blow out the candles', N),
    ('the butt of the joke', N),
    ('a doggy bag', N),
    ('missionary work abroad', N),
    ('a topless convertible', N),
    ('topless photos', P),
    ('a dickpic', U),
    ('sent dickpics', U),
    ('Sex: Female', N),
    ('we talked about sex', N),
    ('the sex of the baby', N),
    ('having sex with the lights on', P),
    ('sex is a taboo topic', N),
    ('she was hooked up to an IV', N),
    ("let's hook up next week to discuss the project", N),
    ('can we hook up tomorrow to talk?', N),
    ('Hancock and the peacock at the cocktail bar', N),
    ('a porn star', U),
    ('he called his boss a dick in standup', N),
]


@pytest.mark.parametrize("text, tier", CASES, ids=[str(i) for i in range(len(CASES))])
def test_each_sentence_gets_its_verdict(text, tier):
    verdict = evaluate(text)
    assert verdict == Verdict(tier is not None, tier), (text, verdict)


@pytest.mark.parametrize("text, tier", CASES, ids=[str(i) for i in range(len(CASES))])
def test_the_one_search_shortcut_never_changes_a_verdict(text, tier):
    """``_may_flag`` only decides whether a text is tokenised at all; reading every word must agree."""
    assert evaluate(text) == evaluate(text, prefilter=False)


def test_both_directions_are_covered_for_every_ambiguous_word():
    """Every framed (ambiguous) word, each form of it, has a sentence that flags and one that does not. A guarded
    word flags in at least one sentence, and each guard has a sentence its ordinary collocation keeps clear."""
    def words(tier_wanted):
        return {w for text, tier in CASES if (tier is not None) == tier_wanted
                for w in ew._Text(ew.normalise(text)).low}

    flagged, clear = words(True), words(False)
    framed = set(ew._FRAMED)
    assert framed <= flagged, sorted(framed - flagged)
    assert framed <= clear, sorted(framed - clear)
    guarded = set(ew._GUARDED)
    assert guarded <= flagged, sorted(guarded - flagged)
    guards = {}
    for word, handler in ew._GUARDED.items():
        guards.setdefault(handler, set()).add(word)
    unguarded = [handler.__name__ for handler, forms in guards.items() if not forms & clear]
    assert not unguarded, unguarded


def test_what_is_not_text_does_not_flag():
    for value in (None, 12, 1.5, b"porn", ["porn"], {"text": "porn"}, "", "   ", "\n\t"):
        assert evaluate(value) == Verdict(False, None)


def test_the_rule_is_a_named_version_and_the_tiers_are_two():
    assert RULE_ID == "explicit-wording/v1" and RULE_ID.startswith(ew.RULE_FAMILY)
    assert {TIER_UNAMBIGUOUS, TIER_PHRASE} == {"unambiguous", "phrase"}
    assert not ew.UNAMBIGUOUS & (set(ew._GUARDED) | set(ew._FRAMED))


def test_unambiguous_wins_over_a_phrase_in_the_same_text():
    assert evaluate("we had sex and then he asked for a blowjob").tier == U


def test_the_rule_reads_the_whole_text_not_its_head():
    head = "An ordinary sentence about the weather. " * 40
    assert len(head) > 512
    assert evaluate(head + "they were sexting all night").tier == U
    assert evaluate(head + "and then we had sex").tier == P


def test_normalisation_mirrors_the_off_limits_boundary():
    """The boundary's pinned tables and this module's copies are one and the same; a change to one fails here."""
    from topos.permissions_v2 import entity_boundary

    assert ew._IGNORABLE == entity_boundary._IGNORABLE
    assert ew._LOOKALIKES == entity_boundary.CONFUSABLES
    assert ew.normalise("ascii stays") == "ascii stays"
    assert ew.normalise("h\u043erny") == "horny"          # a Cyrillic look-alike letter
    assert ew.normalise("ho\u200brny") == "horny"         # a zero-width space
    assert ew.normalise("\uff53\uff45\uff58") == "sex"      # fullwidth letters
    assert ew.normalise("caf\u00e9") == "cafe"             # combining marks dropped after decomposition
    assert ew.normalise("I\u2019m") == "I'm"


def test_a_clause_boundary_ends_every_phrase():
    assert evaluate("we had. sex") == Verdict(False, None)
    assert evaluate("turned\non") == Verdict(False, None)
    assert evaluate("(we had sex)").tier == P
    assert evaluate("we *had sex*").tier == P


def test_the_module_imports_no_model_and_no_settings():
    src = inspect.getsource(ew)
    for forbidden in ("torch", "transformers", "settings", "sqlite3", "httpx", "ollama"):
        assert forbidden not in src, forbidden
